name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install node package, `unity-verify-code`
      run: npm install --global unity-verify-code

    - run: npm install

    - name: Test
      run: node ./lib/cli.js ${{ secrets.EMAIL }} ${{ secrets.PASSWORD }} ./test/fixtures/Unity_v2021.1.1f1.alf

    - name: Expose error screenshot (if any)
      continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: 'error.png'
        path: 'error.png'

    - name: Expose error HTML (if any)
      continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: 'error.html'
        path: 'error.html'
